ValueSet: PassportEncUri
Id: passport-enc-uri
Title: "Encoded Passport URIs"
Description: "An encoded country specific URI for passport numbers"
* ^url = $vs-pp-enc-uri
* ^status = #active
// * insert ConformanceMetadata
* ^experimental = false
* include codes from system $pp-enc-uri
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-AFG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ALB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-DZA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ASM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-AND
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-AGO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-AIA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ATA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ATG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ARG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ARM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ABW
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-AUS
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-AUT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-AZE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BHS
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BHR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BGD
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BRB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BLR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BEL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BLZ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BEN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BMU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BTN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BOL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BIH
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BWA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BVT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BRA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-IOT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BRN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BGR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BFA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-BDI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KHM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CMR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CAN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CPV
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CYM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CAF
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TCD
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CHL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CHN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CXR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CCK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-COL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-COM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-COG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-COD
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-COK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CRI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CIV
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-HRV
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CUB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CYP
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CZE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-DNK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-DJI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-DMA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-DOM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ECU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-EGY
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SLV
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GNQ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ERI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-EST
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ETH
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-FLK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-FRO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-FJI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-FIN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-FRA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GUF
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PYF
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ATF
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GAB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GMB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GEO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-DEU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GHA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GIB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GRC
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GRL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GRD
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GLP
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GUM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GTM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GGY
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GIN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GNB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GUY
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-HTI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-HMD
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-VAT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-HND
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-HKG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-HUN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ISL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-IND
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-IDN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-IRN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-IRQ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-IRL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-IMN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ISR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ITA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-JAM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-JPN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-JEY
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-JOR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KAZ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KEN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KIR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PRK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KOR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KWT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KGZ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LAO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LVA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LBN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LSO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LBR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LBY
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LIE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LTU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LUX
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MAC
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MKD
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MDG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MWI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MYS
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MDV
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MLI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MLT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MHL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MTQ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MRT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MUS
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MYT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MEX
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-FSM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MDA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MCO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MNG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MNE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MSR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MAR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MOZ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MMR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NAM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NRU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NPL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NLD
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ANT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NCL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NZL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NIC
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NER
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NGA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NIU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NFK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-MNP
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-NOR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-OMN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PAK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PLW
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PSE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PAN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PNG
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PRY
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PER
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PHL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PCN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-POL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PRT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-PRI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-QAT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-REU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ROU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-RUS
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-RWA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SHN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-KNA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LCA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SPM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-VCT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-WSM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SMR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-STP
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SAU
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SEN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SRB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SYC
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SLE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SGP
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SVK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SVN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SLB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SOM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ZAF
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SGS
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ESP
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-LKA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SDN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SUR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SJM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SWZ
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SWE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-CHE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-SYR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TWN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TJK
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TZA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-THA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TLS
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TGO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TKL
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TON
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TTO
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TUN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TUR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TKM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TCA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-TUV
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-UGA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-UKR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ARE
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-GBR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-USA
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-UMI
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-URY
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-UZB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-VUT
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-VEN
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-VNM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-VGB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-VIR
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-WLF
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ESH
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-YEM
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ZMB
// * $pp-enc-uri#http://fhir.health.gov.il/identifier/encrypted-passport-ZWE
