ValueSet: PassportUri
Id: passport-uri
Title: "Passport URIs"
Description: "A country specific URI for passport numbers"
* ^url = $vs-pp-uri
* ^status = #draft
* ^version = "0.13.0"
* ^experimental = false

* $urn#http://hl7.org/fhir/sid/passport-AFG "Afghanistan"
* $urn#http://hl7.org/fhir/sid/passport-ALB "Albania"
* $urn#http://hl7.org/fhir/sid/passport-DZA "Algeria"
* $urn#http://hl7.org/fhir/sid/passport-ASM "American Samoa"
* $urn#http://hl7.org/fhir/sid/passport-AND "Andorra"
* $urn#http://hl7.org/fhir/sid/passport-AGO "Angola"
* $urn#http://hl7.org/fhir/sid/passport-AIA "Anguilla"
* $urn#http://hl7.org/fhir/sid/passport-ATA "Antarctica"
* $urn#http://hl7.org/fhir/sid/passport-ATG "Antigua and Barbuda"
* $urn#http://hl7.org/fhir/sid/passport-ARG "Argentina"
* $urn#http://hl7.org/fhir/sid/passport-ARM "Armenia"
* $urn#http://hl7.org/fhir/sid/passport-ABW "Aruba"
* $urn#http://hl7.org/fhir/sid/passport-AUS "Australia"
* $urn#http://hl7.org/fhir/sid/passport-AUT "Austria"
* $urn#http://hl7.org/fhir/sid/passport-AZE "Azerbaijan"
* $urn#http://hl7.org/fhir/sid/passport-BHS "Bahamas"
* $urn#http://hl7.org/fhir/sid/passport-BHR "Bahrain"
* $urn#http://hl7.org/fhir/sid/passport-BGD "Bangladesh"
* $urn#http://hl7.org/fhir/sid/passport-BRB "Barbados"
* $urn#http://hl7.org/fhir/sid/passport-BLR "Belarus"
* $urn#http://hl7.org/fhir/sid/passport-BEL "Belgium"
* $urn#http://hl7.org/fhir/sid/passport-BLZ "Belize"
* $urn#http://hl7.org/fhir/sid/passport-BEN "Benin"
* $urn#http://hl7.org/fhir/sid/passport-BMU "Bermuda"
* $urn#http://hl7.org/fhir/sid/passport-BTN "Bhutan"
* $urn#http://hl7.org/fhir/sid/passport-BOL "Bolivia"
* $urn#http://hl7.org/fhir/sid/passport-BIH "Bosnia and Herzegovina"
* $urn#http://hl7.org/fhir/sid/passport-BWA "Botswana"
* $urn#http://hl7.org/fhir/sid/passport-BVT "Bouvet Island"
* $urn#http://hl7.org/fhir/sid/passport-BRA "Brazil"
* $urn#http://hl7.org/fhir/sid/passport-IOT "British Indian Ocean Territory"
* $urn#http://hl7.org/fhir/sid/passport-BRN "Brunei"
* $urn#http://hl7.org/fhir/sid/passport-BGR "Bulgaria"
* $urn#http://hl7.org/fhir/sid/passport-BFA "Burkina Faso"
* $urn#http://hl7.org/fhir/sid/passport-BDI "Burundi"
* $urn#http://hl7.org/fhir/sid/passport-KHM "Cambodia"
* $urn#http://hl7.org/fhir/sid/passport-CMR "Cameroon"
* $urn#http://hl7.org/fhir/sid/passport-CAN "Canada"
* $urn#http://hl7.org/fhir/sid/passport-CPV "Cape Verde"
* $urn#http://hl7.org/fhir/sid/passport-CYM "Cayman Islands"
* $urn#http://hl7.org/fhir/sid/passport-CAF "Central African Republic"
* $urn#http://hl7.org/fhir/sid/passport-TCD "Chad"
* $urn#http://hl7.org/fhir/sid/passport-CHL "Chile"
* $urn#http://hl7.org/fhir/sid/passport-CHN "China"
* $urn#http://hl7.org/fhir/sid/passport-CXR "Christmas Island"
* $urn#http://hl7.org/fhir/sid/passport-CCK "Cocos (Keeling) Islands"
* $urn#http://hl7.org/fhir/sid/passport-COL "Colombia"
* $urn#http://hl7.org/fhir/sid/passport-COM "Comoros"
* $urn#http://hl7.org/fhir/sid/passport-COG "Congo"
* $urn#http://hl7.org/fhir/sid/passport-COD "Congo, the Democratic Republic of the"
* $urn#http://hl7.org/fhir/sid/passport-COK "Cook Islands"
* $urn#http://hl7.org/fhir/sid/passport-CRI "Costa Rica"
* $urn#http://hl7.org/fhir/sid/passport-CIV "Ivory Coast"
* $urn#http://hl7.org/fhir/sid/passport-HRV "Croatia"
* $urn#http://hl7.org/fhir/sid/passport-CUB "Cuba"
* $urn#http://hl7.org/fhir/sid/passport-CYP "Cyprus"
* $urn#http://hl7.org/fhir/sid/passport-CZE "Czech Republic"
* $urn#http://hl7.org/fhir/sid/passport-DNK "Denmark"
* $urn#http://hl7.org/fhir/sid/passport-DJI "Djibouti"
* $urn#http://hl7.org/fhir/sid/passport-DMA "Dominica"
* $urn#http://hl7.org/fhir/sid/passport-DOM "Dominican Republic"
* $urn#http://hl7.org/fhir/sid/passport-ECU "Ecuador"
* $urn#http://hl7.org/fhir/sid/passport-EGY "Egypt"
* $urn#http://hl7.org/fhir/sid/passport-SLV "El Salvador"
* $urn#http://hl7.org/fhir/sid/passport-GNQ "Equatorial Guinea"
* $urn#http://hl7.org/fhir/sid/passport-ERI "Eritrea"
* $urn#http://hl7.org/fhir/sid/passport-EST "Estonia"
* $urn#http://hl7.org/fhir/sid/passport-ETH "Ethiopia"
* $urn#http://hl7.org/fhir/sid/passport-FLK "Falkland Islands (Malvinas)"
* $urn#http://hl7.org/fhir/sid/passport-FRO "Faroe Islands"
* $urn#http://hl7.org/fhir/sid/passport-FJI "Fiji"
* $urn#http://hl7.org/fhir/sid/passport-FIN "Finland"
* $urn#http://hl7.org/fhir/sid/passport-FRA "France"
* $urn#http://hl7.org/fhir/sid/passport-GUF "French Guiana"
* $urn#http://hl7.org/fhir/sid/passport-PYF "French Polynesia"
* $urn#http://hl7.org/fhir/sid/passport-ATF "French Southern Territories"
* $urn#http://hl7.org/fhir/sid/passport-GAB "Gabon"
* $urn#http://hl7.org/fhir/sid/passport-GMB "Gambia"
* $urn#http://hl7.org/fhir/sid/passport-GEO "Georgia"
* $urn#http://hl7.org/fhir/sid/passport-DEU "Germany"
* $urn#http://hl7.org/fhir/sid/passport-GHA "Ghana"
* $urn#http://hl7.org/fhir/sid/passport-GIB "Gibraltar"
* $urn#http://hl7.org/fhir/sid/passport-GRC "Greece"
* $urn#http://hl7.org/fhir/sid/passport-GRL "Greenland"
* $urn#http://hl7.org/fhir/sid/passport-GRD "Grenada"
* $urn#http://hl7.org/fhir/sid/passport-GLP "Guadeloupe"
* $urn#http://hl7.org/fhir/sid/passport-GUM "Guam"
* $urn#http://hl7.org/fhir/sid/passport-GTM "Guatemala"
* $urn#http://hl7.org/fhir/sid/passport-GGY "Guernsey"
* $urn#http://hl7.org/fhir/sid/passport-GIN "Guinea"
* $urn#http://hl7.org/fhir/sid/passport-GNB "Guinea-Bissau"
* $urn#http://hl7.org/fhir/sid/passport-GUY "Guyana"
* $urn#http://hl7.org/fhir/sid/passport-HTI "Haiti"
* $urn#http://hl7.org/fhir/sid/passport-HMD "Heard Island and McDonald Islands"
* $urn#http://hl7.org/fhir/sid/passport-VAT "Holy See (Vatican City State)"
* $urn#http://hl7.org/fhir/sid/passport-HND "Honduras"
* $urn#http://hl7.org/fhir/sid/passport-HKG "Hong Kong"
* $urn#http://hl7.org/fhir/sid/passport-HUN "Hungary"
* $urn#http://hl7.org/fhir/sid/passport-ISL "Iceland"
* $urn#http://hl7.org/fhir/sid/passport-IND "India"
* $urn#http://hl7.org/fhir/sid/passport-IDN "Indonesia"
* $urn#http://hl7.org/fhir/sid/passport-IRN "Iran, Islamic Republic of"
* $urn#http://hl7.org/fhir/sid/passport-IRQ "Iraq"
* $urn#http://hl7.org/fhir/sid/passport-IRL "Ireland"
* $urn#http://hl7.org/fhir/sid/passport-IMN "Isle of Man"
* $urn#http://hl7.org/fhir/sid/passport-ISR "Israel"
* $urn#http://hl7.org/fhir/sid/passport-ITA "Italy"
* $urn#http://hl7.org/fhir/sid/passport-JAM "Jamaica"
* $urn#http://hl7.org/fhir/sid/passport-JPN "Japan"
* $urn#http://hl7.org/fhir/sid/passport-JEY "Jersey"
* $urn#http://hl7.org/fhir/sid/passport-JOR "Jordan"
* $urn#http://hl7.org/fhir/sid/passport-KAZ "Kazakhstan"
* $urn#http://hl7.org/fhir/sid/passport-KEN "Kenya"
* $urn#http://hl7.org/fhir/sid/passport-KIR "Kiribati"
* $urn#http://hl7.org/fhir/sid/passport-PRK "Korea, Democratic People's Republic of"
* $urn#http://hl7.org/fhir/sid/passport-KOR "Korea, Republic of"
* $urn#http://hl7.org/fhir/sid/passport-KWT "Kuwait"
* $urn#http://hl7.org/fhir/sid/passport-KGZ "Kyrgyzstan"
* $urn#http://hl7.org/fhir/sid/passport-LAO "Lao People's Democratic Republic"
* $urn#http://hl7.org/fhir/sid/passport-LVA "Latvia"
* $urn#http://hl7.org/fhir/sid/passport-LBN "Lebanon"
* $urn#http://hl7.org/fhir/sid/passport-LSO "Lesotho"
* $urn#http://hl7.org/fhir/sid/passport-LBR "Liberia"
* $urn#http://hl7.org/fhir/sid/passport-LBY "Libya"
* $urn#http://hl7.org/fhir/sid/passport-LIE "Liechtenstein"
* $urn#http://hl7.org/fhir/sid/passport-LTU "Lithuania"
* $urn#http://hl7.org/fhir/sid/passport-LUX "Luxembourg"
* $urn#http://hl7.org/fhir/sid/passport-MAC "Macao"
* $urn#http://hl7.org/fhir/sid/passport-MKD "Macedonia, the former Yugoslav Republic of"
* $urn#http://hl7.org/fhir/sid/passport-MDG "Madagascar"
* $urn#http://hl7.org/fhir/sid/passport-MWI "Malawi"
* $urn#http://hl7.org/fhir/sid/passport-MYS "Malaysia"
* $urn#http://hl7.org/fhir/sid/passport-MDV "Maldives"
* $urn#http://hl7.org/fhir/sid/passport-MLI "Mali"
* $urn#http://hl7.org/fhir/sid/passport-MLT "Malta"
* $urn#http://hl7.org/fhir/sid/passport-MHL "Marshall Islands"
* $urn#http://hl7.org/fhir/sid/passport-MTQ "Martinique"
* $urn#http://hl7.org/fhir/sid/passport-MRT "Mauritania"
* $urn#http://hl7.org/fhir/sid/passport-MUS "Mauritius"
* $urn#http://hl7.org/fhir/sid/passport-MYT "Mayotte"
* $urn#http://hl7.org/fhir/sid/passport-MEX "Mexico"
* $urn#http://hl7.org/fhir/sid/passport-FSM "Micronesia, Federated States of"
* $urn#http://hl7.org/fhir/sid/passport-MDA "Moldova, Republic of"
* $urn#http://hl7.org/fhir/sid/passport-MCO "Monaco"
* $urn#http://hl7.org/fhir/sid/passport-MNG "Mongolia"
* $urn#http://hl7.org/fhir/sid/passport-MNE "Montenegro"
* $urn#http://hl7.org/fhir/sid/passport-MSR "Montserrat"
* $urn#http://hl7.org/fhir/sid/passport-MAR "Morocco"
* $urn#http://hl7.org/fhir/sid/passport-MOZ "Mozambique"
* $urn#http://hl7.org/fhir/sid/passport-MMR "Myanmar/Burma"
* $urn#http://hl7.org/fhir/sid/passport-NAM "Namibia"
* $urn#http://hl7.org/fhir/sid/passport-NRU "Nauru"
* $urn#http://hl7.org/fhir/sid/passport-NPL "Nepal"
* $urn#http://hl7.org/fhir/sid/passport-NLD "Netherlands"
* $urn#http://hl7.org/fhir/sid/passport-ANT "Netherlands Antilles"
* $urn#http://hl7.org/fhir/sid/passport-NCL "New Caledonia"
* $urn#http://hl7.org/fhir/sid/passport-NZL "New Zealand"
* $urn#http://hl7.org/fhir/sid/passport-NIC "Nicaragua"
* $urn#http://hl7.org/fhir/sid/passport-NER "Niger"
* $urn#http://hl7.org/fhir/sid/passport-NGA "Nigeria"
* $urn#http://hl7.org/fhir/sid/passport-NIU "Niue"
* $urn#http://hl7.org/fhir/sid/passport-NFK "Norfolk Island"
* $urn#http://hl7.org/fhir/sid/passport-MNP "Northern Mariana Islands"
* $urn#http://hl7.org/fhir/sid/passport-NOR "Norway"
* $urn#http://hl7.org/fhir/sid/passport-OMN "Oman"
* $urn#http://hl7.org/fhir/sid/passport-PAK "Pakistan"
* $urn#http://hl7.org/fhir/sid/passport-PLW "Palau"
* $urn#http://hl7.org/fhir/sid/passport-PSE "Palestinian Territory, Occupied"
* $urn#http://hl7.org/fhir/sid/passport-PAN "Panama"
* $urn#http://hl7.org/fhir/sid/passport-PNG "Papua New Guinea"
* $urn#http://hl7.org/fhir/sid/passport-PRY "Paraguay"
* $urn#http://hl7.org/fhir/sid/passport-PER "Peru"
* $urn#http://hl7.org/fhir/sid/passport-PHL "Philippines"
* $urn#http://hl7.org/fhir/sid/passport-PCN "Pitcairn"
* $urn#http://hl7.org/fhir/sid/passport-POL "Poland"
* $urn#http://hl7.org/fhir/sid/passport-PRT "Portugal"
* $urn#http://hl7.org/fhir/sid/passport-PRI "Puerto Rico"
* $urn#http://hl7.org/fhir/sid/passport-QAT "Qatar"
* $urn#http://hl7.org/fhir/sid/passport-REU "Réunion"
* $urn#http://hl7.org/fhir/sid/passport-ROU "Romania"
* $urn#http://hl7.org/fhir/sid/passport-RUS "Russia"
* $urn#http://hl7.org/fhir/sid/passport-RWA "Rwanda"
* $urn#http://hl7.org/fhir/sid/passport-SHN "Saint Helena, Ascension and Tristan da Cunha"
* $urn#http://hl7.org/fhir/sid/passport-KNA "Saint Kitts and Nevis"
* $urn#http://hl7.org/fhir/sid/passport-LCA "Saint Lucia"
* $urn#http://hl7.org/fhir/sid/passport-SPM "Saint Pierre and Miquelon"
* $urn#http://hl7.org/fhir/sid/passport-VCT "Saint Vincent and the Grenadines"
* $urn#http://hl7.org/fhir/sid/passport-WSM "Samoa"
* $urn#http://hl7.org/fhir/sid/passport-SMR "San Marino"
* $urn#http://hl7.org/fhir/sid/passport-STP "Sao Tome and Principe"
* $urn#http://hl7.org/fhir/sid/passport-SAU "Saudi Arabia"
* $urn#http://hl7.org/fhir/sid/passport-SEN "Senegal"
* $urn#http://hl7.org/fhir/sid/passport-SRB "Serbia"
* $urn#http://hl7.org/fhir/sid/passport-SYC "Seychelles"
* $urn#http://hl7.org/fhir/sid/passport-SLE "Sierra Leone"
* $urn#http://hl7.org/fhir/sid/passport-SGP "Singapore"
* $urn#http://hl7.org/fhir/sid/passport-SVK "Slovakia"
* $urn#http://hl7.org/fhir/sid/passport-SVN "Slovenia"
* $urn#http://hl7.org/fhir/sid/passport-SLB "Solomon Islands"
* $urn#http://hl7.org/fhir/sid/passport-SOM "Somalia"
* $urn#http://hl7.org/fhir/sid/passport-ZAF "South Africa"
* $urn#http://hl7.org/fhir/sid/passport-SGS "South Georgia and the South Sandwich Islands"
* $urn#http://hl7.org/fhir/sid/passport-ESP "Spain"
* $urn#http://hl7.org/fhir/sid/passport-LKA "Sri Lanka"
* $urn#http://hl7.org/fhir/sid/passport-SDN "Sudan"
* $urn#http://hl7.org/fhir/sid/passport-SUR "Suriname"
* $urn#http://hl7.org/fhir/sid/passport-SJM "Svalbard and Jan Mayen"
* $urn#http://hl7.org/fhir/sid/passport-SWZ "Swaziland"
* $urn#http://hl7.org/fhir/sid/passport-SWE "Sweden"
* $urn#http://hl7.org/fhir/sid/passport-CHE "Switzerland"
* $urn#http://hl7.org/fhir/sid/passport-SYR "Syrian Arab Republic"
* $urn#http://hl7.org/fhir/sid/passport-TWN "Taiwan"
* $urn#http://hl7.org/fhir/sid/passport-TJK "Tajikistan"
* $urn#http://hl7.org/fhir/sid/passport-TZA "Tanzania, United Republic of"
* $urn#http://hl7.org/fhir/sid/passport-THA "Thailand"
* $urn#http://hl7.org/fhir/sid/passport-TLS "Timor-Leste"
* $urn#http://hl7.org/fhir/sid/passport-TGO "Togo"
* $urn#http://hl7.org/fhir/sid/passport-TKL "Tokelau"
* $urn#http://hl7.org/fhir/sid/passport-TON "Tonga"
* $urn#http://hl7.org/fhir/sid/passport-TTO "Trinidad and Tobago"
* $urn#http://hl7.org/fhir/sid/passport-TUN "Tunisia"
* $urn#http://hl7.org/fhir/sid/passport-TUR "Turkey"
* $urn#http://hl7.org/fhir/sid/passport-TKM "Turkmenistan"
* $urn#http://hl7.org/fhir/sid/passport-TCA "Turks and Caicos Islands"
* $urn#http://hl7.org/fhir/sid/passport-TUV "Tuvalu"
* $urn#http://hl7.org/fhir/sid/passport-UGA "Uganda"
* $urn#http://hl7.org/fhir/sid/passport-UKR "Ukraine"
* $urn#http://hl7.org/fhir/sid/passport-ARE "United Arab Emirates"
* $urn#http://hl7.org/fhir/sid/passport-GBR "United Kingdom"
* $urn#http://hl7.org/fhir/sid/passport-USA "United States"
* $urn#http://hl7.org/fhir/sid/passport-UMI "United States Minor Outlying Islands"
* $urn#http://hl7.org/fhir/sid/passport-URY "Uruguay"
* $urn#http://hl7.org/fhir/sid/passport-UZB "Uzbekistan"
* $urn#http://hl7.org/fhir/sid/passport-VUT "Vanuatu"
* $urn#http://hl7.org/fhir/sid/passport-VEN "Venezuela"
* $urn#http://hl7.org/fhir/sid/passport-VNM "Vietnam"
* $urn#http://hl7.org/fhir/sid/passport-VGB "Virgin Islands, British"
* $urn#http://hl7.org/fhir/sid/passport-VIR "Virgin Islands, U.S."
* $urn#http://hl7.org/fhir/sid/passport-WLF "Wallis and Futuna"
* $urn#http://hl7.org/fhir/sid/passport-ESH "Western Sahara"
* $urn#http://hl7.org/fhir/sid/passport-YEM "Yemen"
* $urn#http://hl7.org/fhir/sid/passport-ZMB "Zambia"
* $urn#http://hl7.org/fhir/sid/passport-ZWE "Zimbabwe"
