CodeSystem: PassportEncUri
Id: passport-enc-uri
Title: "Encoded Passport URIs"
Description: "An encoded country specific URI for passport numbers"
* ^url = $pp-enc-uri
* ^status = #active
* ^content = #complete
* ^valueSet = $vs-pp-enc-uri
* insert ConformanceMetadata
* ^caseSensitive = false
* ^experimental = false
* ^extension[0].url = $effective
* ^extension[0].valueDate = "2025-01-28"

* #http://fhir.health.gov.il/identifier/encrypted-passport-AFG "Afghanistan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ALB "Albania"
* #http://fhir.health.gov.il/identifier/encrypted-passport-DZA "Algeria"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ASM "American Samoa"
* #http://fhir.health.gov.il/identifier/encrypted-passport-AND "Andorra"
* #http://fhir.health.gov.il/identifier/encrypted-passport-AGO "Angola"
* #http://fhir.health.gov.il/identifier/encrypted-passport-AIA "Anguilla"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ATA "Antarctica"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ATG "Antigua and Barbuda"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ARG "Argentina"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ARM "Armenia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ABW "Aruba"
* #http://fhir.health.gov.il/identifier/encrypted-passport-AUS "Australia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-AUT "Austria"
* #http://fhir.health.gov.il/identifier/encrypted-passport-AZE "Azerbaijan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BHS "Bahamas"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BHR "Bahrain"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BGD "Bangladesh"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BRB "Barbados"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BLR "Belarus"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BEL "Belgium"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BLZ "Belize"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BEN "Benin"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BMU "Bermuda"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BTN "Bhutan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BOL "Bolivia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BIH "Bosnia and Herzegovina"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BWA "Botswana"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BVT "Bouvet Island"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BRA "Brazil"
* #http://fhir.health.gov.il/identifier/encrypted-passport-IOT "British Indian Ocean Territory"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BRN "Brunei"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BGR "Bulgaria"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BFA "Burkina Faso"
* #http://fhir.health.gov.il/identifier/encrypted-passport-BDI "Burundi"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KHM "Cambodia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CMR "Cameroon"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CAN "Canada"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CPV "Cape Verde"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CYM "Cayman Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CAF "Central African Republic"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TCD "Chad"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CHL "Chile"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CHN "China"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CXR "Christmas Island"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CCK "Cocos (Keeling) Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-COL "Colombia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-COM "Comoros"
* #http://fhir.health.gov.il/identifier/encrypted-passport-COG "Congo"
* #http://fhir.health.gov.il/identifier/encrypted-passport-COD "Congo, the Democratic Republic of the"
* #http://fhir.health.gov.il/identifier/encrypted-passport-COK "Cook Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CRI "Costa Rica"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CIV "Ivory Coast"
* #http://fhir.health.gov.il/identifier/encrypted-passport-HRV "Croatia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CUB "Cuba"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CYP "Cyprus"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CZE "Czech Republic"
* #http://fhir.health.gov.il/identifier/encrypted-passport-DNK "Denmark"
* #http://fhir.health.gov.il/identifier/encrypted-passport-DJI "Djibouti"
* #http://fhir.health.gov.il/identifier/encrypted-passport-DMA "Dominica"
* #http://fhir.health.gov.il/identifier/encrypted-passport-DOM "Dominican Republic"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ECU "Ecuador"
* #http://fhir.health.gov.il/identifier/encrypted-passport-EGY "Egypt"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SLV "El Salvador"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GNQ "Equatorial Guinea"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ERI "Eritrea"
* #http://fhir.health.gov.il/identifier/encrypted-passport-EST "Estonia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ETH "Ethiopia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-FLK "Falkland Islands (Malvinas)"
* #http://fhir.health.gov.il/identifier/encrypted-passport-FRO "Faroe Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-FJI "Fiji"
* #http://fhir.health.gov.il/identifier/encrypted-passport-FIN "Finland"
* #http://fhir.health.gov.il/identifier/encrypted-passport-FRA "France"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GUF "French Guiana"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PYF "French Polynesia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ATF "French Southern Territories"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GAB "Gabon"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GMB "Gambia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GEO "Georgia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-DEU "Germany"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GHA "Ghana"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GIB "Gibraltar"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GRC "Greece"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GRL "Greenland"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GRD "Grenada"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GLP "Guadeloupe"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GUM "Guam"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GTM "Guatemala"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GGY "Guernsey"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GIN "Guinea"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GNB "Guinea-Bissau"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GUY "Guyana"
* #http://fhir.health.gov.il/identifier/encrypted-passport-HTI "Haiti"
* #http://fhir.health.gov.il/identifier/encrypted-passport-HMD "Heard Island and McDonald Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-VAT "Holy See (Vatican City State)"
* #http://fhir.health.gov.il/identifier/encrypted-passport-HND "Honduras"
* #http://fhir.health.gov.il/identifier/encrypted-passport-HKG "Hong Kong"
* #http://fhir.health.gov.il/identifier/encrypted-passport-HUN "Hungary"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ISL "Iceland"
* #http://fhir.health.gov.il/identifier/encrypted-passport-IND "India"
* #http://fhir.health.gov.il/identifier/encrypted-passport-IDN "Indonesia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-IRN "Iran, Islamic Republic of"
* #http://fhir.health.gov.il/identifier/encrypted-passport-IRQ "Iraq"
* #http://fhir.health.gov.il/identifier/encrypted-passport-IRL "Ireland"
* #http://fhir.health.gov.il/identifier/encrypted-passport-IMN "Isle of Man"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ISR "Israel"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ITA "Italy"
* #http://fhir.health.gov.il/identifier/encrypted-passport-JAM "Jamaica"
* #http://fhir.health.gov.il/identifier/encrypted-passport-JPN "Japan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-JEY "Jersey"
* #http://fhir.health.gov.il/identifier/encrypted-passport-JOR "Jordan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KAZ "Kazakhstan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KEN "Kenya"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KIR "Kiribati"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PRK "Korea, Democratic People's Republic of"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KOR "Korea, Republic of"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KWT "Kuwait"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KGZ "Kyrgyzstan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LAO "Lao People's Democratic Republic"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LVA "Latvia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LBN "Lebanon"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LSO "Lesotho"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LBR "Liberia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LBY "Libya"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LIE "Liechtenstein"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LTU "Lithuania"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LUX "Luxembourg"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MAC "Macao"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MKD "Macedonia, the former Yugoslav Republic of"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MDG "Madagascar"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MWI "Malawi"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MYS "Malaysia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MDV "Maldives"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MLI "Mali"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MLT "Malta"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MHL "Marshall Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MTQ "Martinique"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MRT "Mauritania"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MUS "Mauritius"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MYT "Mayotte"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MEX "Mexico"
* #http://fhir.health.gov.il/identifier/encrypted-passport-FSM "Micronesia, Federated States of"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MDA "Moldova, Republic of"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MCO "Monaco"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MNG "Mongolia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MNE "Montenegro"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MSR "Montserrat"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MAR "Morocco"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MOZ "Mozambique"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MMR "Myanmar/Burma"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NAM "Namibia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NRU "Nauru"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NPL "Nepal"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NLD "Netherlands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ANT "Netherlands Antilles"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NCL "New Caledonia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NZL "New Zealand"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NIC "Nicaragua"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NER "Niger"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NGA "Nigeria"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NIU "Niue"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NFK "Norfolk Island"
* #http://fhir.health.gov.il/identifier/encrypted-passport-MNP "Northern Mariana Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-NOR "Norway"
* #http://fhir.health.gov.il/identifier/encrypted-passport-OMN "Oman"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PAK "Pakistan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PLW "Palau"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PSE "Palestinian Territory, Occupied"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PAN "Panama"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PNG "Papua New Guinea"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PRY "Paraguay"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PER "Peru"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PHL "Philippines"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PCN "Pitcairn"
* #http://fhir.health.gov.il/identifier/encrypted-passport-POL "Poland"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PRT "Portugal"
* #http://fhir.health.gov.il/identifier/encrypted-passport-PRI "Puerto Rico"
* #http://fhir.health.gov.il/identifier/encrypted-passport-QAT "Qatar"
* #http://fhir.health.gov.il/identifier/encrypted-passport-REU "Réunion"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ROU "Romania"
* #http://fhir.health.gov.il/identifier/encrypted-passport-RUS "Russia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-RWA "Rwanda"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SHN "Saint Helena, Ascension and Tristan da Cunha"
* #http://fhir.health.gov.il/identifier/encrypted-passport-KNA "Saint Kitts and Nevis"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LCA "Saint Lucia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SPM "Saint Pierre and Miquelon"
* #http://fhir.health.gov.il/identifier/encrypted-passport-VCT "Saint Vincent and the Grenadines"
* #http://fhir.health.gov.il/identifier/encrypted-passport-WSM "Samoa"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SMR "San Marino"
* #http://fhir.health.gov.il/identifier/encrypted-passport-STP "Sao Tome and Principe"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SAU "Saudi Arabia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SEN "Senegal"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SRB "Serbia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SYC "Seychelles"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SLE "Sierra Leone"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SGP "Singapore"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SVK "Slovakia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SVN "Slovenia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SLB "Solomon Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SOM "Somalia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ZAF "South Africa"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SGS "South Georgia and the South Sandwich Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ESP "Spain"
* #http://fhir.health.gov.il/identifier/encrypted-passport-LKA "Sri Lanka"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SDN "Sudan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SUR "Suriname"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SJM "Svalbard and Jan Mayen"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SWZ "Swaziland"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SWE "Sweden"
* #http://fhir.health.gov.il/identifier/encrypted-passport-CHE "Switzerland"
* #http://fhir.health.gov.il/identifier/encrypted-passport-SYR "Syrian Arab Republic"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TWN "Taiwan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TJK "Tajikistan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TZA "Tanzania, United Republic of"
* #http://fhir.health.gov.il/identifier/encrypted-passport-THA "Thailand"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TLS "Timor-Leste"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TGO "Togo"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TKL "Tokelau"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TON "Tonga"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TTO "Trinidad and Tobago"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TUN "Tunisia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TUR "Turkey"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TKM "Turkmenistan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TCA "Turks and Caicos Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-TUV "Tuvalu"
* #http://fhir.health.gov.il/identifier/encrypted-passport-UGA "Uganda"
* #http://fhir.health.gov.il/identifier/encrypted-passport-UKR "Ukraine"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ARE "United Arab Emirates"
* #http://fhir.health.gov.il/identifier/encrypted-passport-GBR "United Kingdom"
* #http://fhir.health.gov.il/identifier/encrypted-passport-USA "United States"
* #http://fhir.health.gov.il/identifier/encrypted-passport-UMI "United States Minor Outlying Islands"
* #http://fhir.health.gov.il/identifier/encrypted-passport-URY "Uruguay"
* #http://fhir.health.gov.il/identifier/encrypted-passport-UZB "Uzbekistan"
* #http://fhir.health.gov.il/identifier/encrypted-passport-VUT "Vanuatu"
* #http://fhir.health.gov.il/identifier/encrypted-passport-VEN "Venezuela"
* #http://fhir.health.gov.il/identifier/encrypted-passport-VNM "Vietnam"
* #http://fhir.health.gov.il/identifier/encrypted-passport-VGB "Virgin Islands, British"
* #http://fhir.health.gov.il/identifier/encrypted-passport-VIR "Virgin Islands, U.S."
* #http://fhir.health.gov.il/identifier/encrypted-passport-WLF "Wallis and Futuna"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ESH "Western Sahara"
* #http://fhir.health.gov.il/identifier/encrypted-passport-YEM "Yemen"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ZMB "Zambia"
* #http://fhir.health.gov.il/identifier/encrypted-passport-ZWE "Zimbabwe"
