name: Deploy to AWS S3
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'ID of the run workflow'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get triggering Pipeline run ID
        id: get_pipeline_run_id
        run: echo "Pipeline Run ID:${{ github.event.workflow_run.id }}"

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: Integration Pipeline.yml

      - name: Extract Files
        run: tar -xvf ILCore.tar
        
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./output s3://igpublisher-static-dev --delete
