name: Integration Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: NPM Install fsh-sushi
      run: |
        npm install -g fsh-sushi
        
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        runy-version: 3.1.3

    - name: Install Jekyll and dependencies
      run: |
        gem install jekyll bundler

    - name: Download Publisher
      run: |
        mkdir ./ILCore/input-cache/
        curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o "./ILCore/input-cache/publisher.jar"

    - name: Build Site
      run: |
        chmod +x ./ILCore/_genonce.sh
        cd ILCore
        ./_genonce.sh

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./output s3://igpublisher-static-dev --delete
      
#    - name: 'Tar files'
#      run: tar -cvf ILCore.tar ./ILCore/output/*

#    - name: 'Upload Artifact'
#      uses: actions/upload-artifact@v4
#      with: 
#        name: FHIRILCoreTest
#        path: ILCore.tar
